# Default initial positions for crx_bimanual's ros2_control fake system

initial_positions:
  left_J1: 0
  left_J2: 0
  left_J3: 0
  left_J4: 0
  left_J5: 0
  left_J6: 0
  right_J1: 0
  right_J2: 0
  right_J3: 0
  right_J4: 0
  right_J5: 0
  right_J6: 0