# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_manipulator_controller
    - right_manipulator_controller

  left_manipulator_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - left_J1
      - left_J2
      - left_J3
      - left_J4
      - left_J5
      - left_J6
  right_manipulator_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - right_J1
      - right_J2
      - right_J3
      - right_J4
      - right_J5
      - right_J6