# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_manipulator_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_manipulator_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    forward_position_controller:
      type: position_controllers/JointGroupPositionController

left_manipulator_controller:
  ros__parameters:
    joints:
      - left_J1
      - left_J2
      - left_J3
      - left_J4
      - left_J5
      - left_J6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_manipulator_controller:
  ros__parameters:
    joints:
      - right_J1
      - right_J2
      - right_J3
      - right_J4
      - right_J5
      - right_J6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity